cloudformation/online-trial-control.yaml

I forgot to remove the reference of an old param

TAA-822 - Fix build error

---

.gitignore

Just some gitignore basics for editors and q+d hacking files.

Basics for .gitignore

---

cloudformation/online-trial-stack.yaml

Installation, configuration and provisioning. Script only accessible from trials VPC

Added Wazuh agent

---

cloudformation/online-trial-control.yaml
cloudformation/online-trial-stack.yaml

- Temporary removal of monitoring agents.
Build success on test here https://bamboo.alfresco.com/bamboo/browse/DEVOPS-OTA-93

Release v1.1.2

---

cloudformation/online-trial-control.yaml
cloudformation/online-trial-stack.yaml

- Reduce functions per trial stack count from 5 to 0
- New AMI for production
Test release here: https://bamboo.alfresco.com/bamboo/browse/DEVOPS-OTA-95
AMI release here: https://bamboo.alfresco.com/bamboo/browse/DEVOPS-TRIALS1-DS-12

Release v1.2.0

---

cloudformation/online-trial-control.yaml
cloudformation/online-trial-stack.yaml

- Fix to LifecycleHandler to stop instances using OpsWorks API

Release v1.3.0

---

cloudformation/online-trial-control.yaml

- Fix to OpsWorksRegister Lambda to check for instance state before calling the correct API

Release v1.3.5

---

cloudformation/online-trial-control.yaml
cloudformation/online-trial-stack.yaml

- Removal of some unneeded dependancies
- Added Cloudwatch event to handle updating/deleting of R53 records on Ec2 Instance state change

Release v1.4.0

---

cloudformation/online-trial-control.yaml

- Added Global Secondary Index to Trial Assigned Dynamo Table.

Release v1.5.0

---

cloudformation/online-trial-control.yaml
cloudformation/online-trial-stack.yaml
cloudformation/ot-stack-createStack.sh
cloudformation/ot-stack-parameters.json

- Tidied up some parameters
- Added DR site capability

Release v1.6.0

---

cloudformation/online-trial-control.yaml

- Added Lifecycle Rules to the templates bucket

Release v1.6.1

---

cloudformation/online-trial-control.yaml
cloudformation/online-trial-stack.yaml
cloudformation/ot-stack-createStack.sh
cloudformation/ot-stack-parameters.json

- New Bucket ARN syntax
- Added Bcrypt password encryption to the trial instances
- Removed unused outputs
- Reverted removed Bamboo AMI integrations

Release v1.7.0

---

cloudformation/online-trial-stack.yaml

Release v1.7.1

---

cloudformation/online-trial-control.yaml
cloudformation/online-trial-stack.yaml

- Use of Managed Policy for API Gateway logging
- New AMI's for Trials

Release v1.7.2

---

cloudformation/online-trial-control.yaml

- Fix to Lambda that created/deletes R53 record sets.

Release v1.7.3

---

cloudformation/online-trial-control.yaml
cloudformation/online-trial-stack.yaml

- Update to fix R53 creation/deletion
- New Trial AMI with Java update 8u141

Release v1.7.4

---

cloudformation/online-trial-stack.yaml

New Trial AMI's with ACS 5.2.1 and GS 2.5.2

Release v1.8.0

---

cloudformation/online-trial-stack.yaml

- Neater code to wait for Opswork instance to be registered

Release V1.7.5

---

cloudformation/online-trial-control.yaml
cloudformation/online-trial-stack.yaml

- ACS 5.2.2
- Tidy up of !If statements

DEVOPS-9150: Release of ACS 5.2.2 Online Trial

---

cloudformation/online-trial-control.yaml
cloudformation/online-trial-stack.yaml
cloudformation/parameters.json

- ACS Version 5.2.2
- Some template tidying

Release v1.7.6

---

cloudformation/online-trial-stack.yaml

NOTE: Still need to review the admin password process with Toni.

MSP-142: Updated trial stack to initialise new docker based AMI

---

cloudformation/online-trial-stack.yaml

Latest AMI with non-SSL nginx ingress

MSP-141 Use "ACS 6.1 Trials AMI - 2018-10-19T13-29-21Z - master - 13"

---

cloudformation/online-trial-stack.yaml

Include MSP-154, MSP-160, MSP-161 and MSP-162.

MSP-162 Use "ACS 6.1 Trials AMI - 2018-10-26T15-22-35Z - master - 19"

---

cloudformation/online-trial-stack.yaml

Updated AMI and UserData to replace protocol, host and port tokens.

MSP-163: Update host properties

---

cloudformation/online-trial-stack.yaml

Updated AMI and introduced check for the digital workspace being ready.

MSP-164: Added missing configuration

---

cloudformation/online-trial-stack.yaml

~Images generated here: https://bamboo.alfresco.com/bamboo/browse/MS-IT-30/log~
Images generated here: https://bamboo.alfresco.com/bamboo/browse/MS-IT-31/log
Combination of updates from MSP-178 MSP-179 MSP-217

MSP-219 EA2 Image

---

cloudformation/online-trial-stack.yaml

Ports have changed. Latest "Build 38" AMIs.

MSP-207 Port changes + AMIs (obvs)

---

cloudformation/online-trial-stack.yaml

MSP-229 and others. Roll out Master 040 build

---

cloudformation/online-trial-stack.yaml

6.1 GA RC1
